# Generated by Django 4.0.5 on 2022-09-10 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('msg', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(choices=[('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental')], max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
