# Generated by Django 4.0.7 on 2022-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('major', models.CharField(max_length=150)),
                ('doc_pic', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
