# Generated by Django 4.0.5 on 2022-09-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_docname_news_newsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
